web:
  host: localhost
  port: 8080
scan:
  script: ./dummy_scan.sh
  temp_directory: temp
crypto:
  request_secret_path: request_secret
download:
  base_homeserver_url: https://matrix-client.matrix.org
