name: Linting and Tests
on:
  push:
    branches: ["main"]
  pull_request:

jobs: 
  check-code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libolm-dev libmagic1
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: python -m pip install tox
      - run: tox -e check_codestyle

  check-types:
    name: Check types with Mypy
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libolm-dev libmagic1
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # We're testing Python 3.10 specifically (instead of 3.x) for this job because
          # python-olm does not have wheels for Python 3.11 yet.
          python-version: "3.10"
      - run: python -m pip install tox
      - run: tox -e check_types

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run the unit tests both against our oldest supported Python version
        # and the newest stable.
        python_version: [ "3.8", "3.x" ]
    steps:
      - run: sudo apt-get install -y libolm-dev libmagic1
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - run: python -m pip install tox
      - run: tox -e py

